Repository Google-Developer-Groups-Siliguri/gdg-siliguri-website, pull requests merged in 2023-10, with the labels that each got.

#18 Feature/devfest hero
  src/app/components/address-map/address-map.component.html
  src/app/components/contact-map/contact-map.component.html
  src/app/components/devfest-hero/devfest-hero.component.css
  src/app/components/devfest-hero/devfest-hero.component.html
  src/app/components/devfest-hero/devfest-hero.component.spec.ts
  src/app/components/devfest-hero/devfest-hero.component.ts
  src/app/components/partners/partners.component.html
  src/app/components/speakers/speakers.component.html
  src/app/components/sponsors/sponsors.component.html
  src/app/pages/devfest/devfest.component.html
  src/app/pages/devfest/devfest.module.ts
  src/assets/images/devfest.png
  src/styles.css
Labels: enhancement, GDG Siliguri Devfest

#20 Schedule
  src/app/components/devfest-hero/devfest-hero.component.ts
  src/app/components/speaker-card/speaker-card.component.html
  src/app/components/timeline/timeline.component.css
  src/app/components/timeline/timeline.component.html
  src/app/components/timeline/timeline.component.spec.ts
  src/app/components/timeline/timeline.component.ts
  src/app/pages/schedule/schedule.component.html
  src/app/pages/schedule/schedule.component.ts
  src/app/pages/schedule/schedule.module.ts
Labels: enhancement, GDG Siliguri Devfest

#28 Feature/whatis
  src/app/components/devfest-hero/devfest-hero.component.html
  src/app/components/navbar-devfest/navbar-devfest.component.css
  src/app/components/navbar-devfest/navbar-devfest.component.html
  src/app/components/navbar-devfest/navbar-devfest.component.ts
  src/app/components/whats-is/whats-is.component.css
  src/app/components/whats-is/whats-is.component.html
  src/app/components/whats-is/whats-is.component.spec.ts
  src/app/components/whats-is/whats-is.component.ts
  src/app/pages/devfest/devfest.component.ts
  src/app/pages/home-page/home-page.component.ts
  src/app/pages/schedule/schedule.component.ts
  src/app/pages/team/team.component.ts
  src/app/pages/tickets/tickets.component.ts
  src/assets/images/header-banner.webp
  src/assets/images/what-is-devfest.webp
Labels: enhancement, GDG Siliguri Devfest

#32 Pwa
  angular.json
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/address-map/address-map.component.html
  src/app/components/contact-map/contact-map.component.html
  src/app/components/whats-is/whats-is.component.html
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/index.html
  src/manifest.webmanifest
Labels: enhancement, GDG Siliguri Devfest

#35 Add padding to the grab your tickets section
  package-lock.json
  src/app/components/devfest-hero/devfest-hero.component.html
  src/app/components/member-card/member-card.component.html
  src/app/pages/contact/contact.component.html
  src/assets/images/header-banner.webp
  src/assets/images/new-banner-mobile.webp
  src/assets/images/new-banner.webp
  src/favicon.ico
  src/favicon.png
  src/index.html
Labels: bug

#36 firebase initial integration for teams and speakers
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/member-card/member-card.component.html
  src/app/components/member-card/member-card.component.ts
  src/app/components/speakers/speakers.component.ts
  src/app/pages/team/team.component.ts
  src/app/services/data.service.spec.ts
  src/app/services/data.service.ts
  src/assets/scripts/setEnv.ts
  src/index.html
Labels: enhancement, GDG Siliguri Devfest

#37 bug fixes, community partners data add through firebase
  src/app/app.component.ts
  src/app/components/member-card/member-card.component.html
  src/app/components/partner-card/partner-card.component.css
  src/app/components/partner-card/partner-card.component.html
  src/app/components/partner-card/partner-card.component.spec.ts
  src/app/components/partner-card/partner-card.component.ts
  src/app/components/partners/partners.component.html
  src/app/components/partners/partners.component.ts
  src/app/components/review/review.component.html
  src/app/components/speakers/speakers.component.html
  src/app/components/speakers/speakers.component.ts
  src/app/pages/team/team.component.html
  src/app/pages/team/team.component.ts
  src/app/pages/tickets/tickets.component.html
  src/app/services/data.service.ts
Labels: bug, enhancement, GDG Siliguri Devfest

#38 add static seo tags, optional seo optimizations: add link description…
  server.ts
  src/app/components/devfest-hero/devfest-hero.component.html
  src/app/components/partner-card/partner-card.component.html
  src/index.html
  src/styles.css
Labels: enhancement, GDG Siliguri Devfest

#39 member card badge fix
  src/app/components/member-card/member-card.component.html
  src/app/components/speakers/speakers.component.html
  src/app/pages/team/team.component.html
Labels: bug, GDG Siliguri Devfest
